--- # my handlers playbook
- hosts: all
  become: true

  tasks:
    - name: installing gttpd into webservers
      action: yum name=httpd state=installed
      notify: start httpd service

  handlers:
    - name: start httpd service
      action: service name=httpd state=started

