--- 
- hosts: all
  become: true

  tasks:
    - name: installing java
      yum:
       name: java
       state: installed

    - name: insalling wget commands
      yum:
        name: wget
        state: installed

    - name: installing jenkins
      get_url: 
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: download jenkins key
      rpm_key: 
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: install jenkins
      yum:
        name: jenkins
        state: installed

    - name: starting jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
