--- 
- hosts: all
  become: true

  tasks:
    - name: installing sw
      yum:
        name=httpd
        state=present

    - name: start service
      service:
       name=httpd
       state=started

